### ISSUE TITLE
Not all notes display on Firefox

### ISSUE THREAD

**Issue by Jademalo** [Angramme/polyrhythm#5]
![image](https://user-images.githubusercontent.com/386846/85912667-2e1ad580-b826-11ea-87f3-1e5b09f8d245.png)

For some reason, when set to 5:4, only the first 4 notes of the 5 grouping will show

**Comment by Angramme** [comment]
Hmmm weird, works fine on my end, do you have the latest version of Firefox? Does the console output any errors? I presume it has something to do with the way SpiderMonkey does math.
![image](https://user-images.githubusercontent.com/34948473/95658707-c0689000-0b1c-11eb-82ed-ba22a69b7149.png)
EDIT: does it still make a sound on the invisible note or is it silent?
EDIT2: sorry for a late reply, I received the notification email only yesterday or something.

**Comment by Jademalo** [comment]
Haha, no problem!
Firefox 81.0.1 64bit, which I assume is the latest.

Interestingly it does still make a sound on the invisible note, it's purely a graphical bug.
There are also no errors on the console from what I can see.

**Comment by Angramme** [comment]
Fixed It! See this commit for details: d5a732e. This issue can now be closed I think 👍

**Comment by Jademalo** [comment]
Perfect, that's fixed it!
